#ifndef FLASH_CONFIG_H
#define FLASH_CONFIG_H

// flash constants for STM32G431CB

#define NUM_FLASH_BANKS 1U
#define NUM_FLASH_PAGES 64U
#define FLASH_PAGE_SIZE_BYTES 2048U
#define FLASH_BEGIN_ADDRESS 0x08000000U
#define FLASH_END_ADDRESS 0x0801FFFFU

// flash regions
#define BOOTLOADER_SIZE_BYTES 0x5000U // 20 KB, pages 0-9
#define FW_SLOT_SIZE_BYTES 0xD800U // 54 KB, 27 pages each

#define BOOTLOADER_START_ADDRESS FLASH_BEGIN_ADDRESS
#define FW_SLOT_A_START_ADDRESS (BOOTLOADER_START_ADDRESS + BOOTLOADER_SIZE_BYTES)
#define FW_SLOT_B_START_ADDRESS (FW_SLOT_A_START_ADDRESS + FW_SLOT_SIZE_BYTES)

#endif