#ifndef SR_ERRNO_H
#define SR_ERRNO_H

typedef enum {
    SR_OK = 0,
    // flash errors
    ERR_FLASH_UNLOCK,
    ERR_FLASH_LOCK,
    ERR_FLASH_WRITE,
    ERR_FLASH_READBACK,
    ERR_FLASH_ERASE,
    ERR_FLASH_INVALID_INPUT,
    ERR_FLASH_WRITER_NOT_STARTED,

    // fd-can errors
    ERR_FDCAN_CFG_GLOBAL_FILTER,
    ERR_FDCAN_CFG_FILTER,
    ERR_FDCAN_OVER_MAX_FILTERS,
    ERR_FDCAN_CFG_FIFO_OVERWRITE,
    ERR_FDCAN_ACTIVATE_NOTIF,
    ERR_FDCAN_TX_MSG_TOO_BIG,
    ERR_FDCAN_TX,
    ERR_FDCAN_TIMEOUT,
    ERR_FDCAN_START,

    // RNG errors
    ERR_RNG_FAIL_START,
    ERR_RNG_FAIL_GEN,

    // isotp errors
    ERR_ISOTP_TX_LEN,
    ERR_ISOTP_INVALID_FRAME,
    ERR_ISOTP_ABORTED_TRANSFER,
    ERR_ISOTP_TRANSMISSION_TOO_LARGE,
    ERR_ISOTP_OUT_OF_ORDER,
    ERR_ISOTP_UNEXPECTED_FRAME_TYPE,
    ERR_ISOTP_RX_BUFF_TOO_SMALL,
    ERR_ISOTP_TIMEOUT,
    ERR_ISOTP_TX_INTERRUPTED_BY_RX

} sr_errno_t;

#endif