#pragma once

/*
    ISO-TP Constants
    ISOTPlib - ISO-TP Library for embedded systems
    ndaria (me@nickdaria.com) @nickdaria

    This file contains constants used in the ISO-TP protocol

    Sources:
        ISO-TP                          https://en.wikipedia.org/wiki/ISO_15765-2
        ISO-TP CAN FD Frame Format      https://en.wikipedia.org/wiki/CAN_FD#CAN_&_CAN_FD_TP_Headers

*/


#ifdef __cplusplus
extern "C" {
#endif

// ISO-TP frame types
typedef enum {
	ISOTP_SPEC_FRAME_SINGLE = 0x00,
	ISOTP_SPEC_FRAME_FIRST = 0x01,
	ISOTP_SPEC_FRAME_CONSECUTIVE = 0x02,
	ISOTP_SPEC_FRAME_FLOW_CONTROL = 0x03
} isotp_spec_frame_type_t;

//  All frames
#define ISOTP_SPEC_FRAME_TYPE_IDX 0
#define ISOTP_SPEC_FRAME_TYPE_MASK 0xF0
#define ISOTP_SPEC_FRAME_TYPE_SHIFT 4

//  Single frame
#define ISOTP_SPEC_FRAME_SINGLE_LEN_IDX 0
#define ISOTP_SPEC_FRAME_SINGLE_LEN_MASK 0x0F

#define ISOTP_SPEC_FRAME_SINGLE_DATASTART_IDX 1

//  Single frame (CAN FD)
#define ISOTP_SPEC_FRAME_SINGLE_FD_ENABLE_LEN 8
#define ISOTP_SPEC_FRAME_SINGLE_FD_LEN_IDX 1
#define ISOTP_SPEC_FRAME_SINGLE_FD_LEN_MASK 0xFF

#define ISOTP_SPEC_FRAME_SINGLE_FD_DATASTART_IDX 2

//  First frame
#define ISOTP_SPEC_FRAME_FIRST_LEN_MSB_IDX 0
#define ISOTP_SPEC_FRAME_FIRST_LEN_MSB_MASK 0x0F

#define ISOTP_SPEC_FRAME_FIRST_LEN_LSB_IDX 1
#define ISOTP_SPEC_FRAME_FIRST_LEN_LSB_MASK 0xFF

#define ISOTP_SPEC_FRAME_FIRST_DATASTART_IDX 2

//  First frame (CAN FD)
#define ISOTP_SPEC_FRAME_FIRST_FD_ENABLE_LEN 0x0FFF
#define ISOTP_SPEC_FRAME_FIRST_FD_MSB_IDX 2
#define ISOTP_SPEC_FRAME_FIRST_FD_LSB_IDX 5
#define ISOTP_SPEC_FRAME_FIRST_FD_DATASTART_IDX 6

//  Consecutive frame
#define ISOTP_SPEC_FRAME_CONSECUTIVE_INDEX_IDX 0
#define ISOTP_SPEC_FRAME_CONSECUTIVE_INDEX_MASK 0x0F

#define ISOTP_SPEC_FRAME_CONSECUTIVE_DATASTART_IDX 1

#define ISOTP_SPEC_FRAME_CONSECUTIVE_INDEXING_START 1
#define ISOTP_SPEC_FRAME_CONSECUTIVE_INDEXING_MIN 0x00
#define ISOTP_SPEC_FRAME_CONSECUTIVE_INDEXING_MAX 0x0F

//  Flow control frame
#define ISOTP_SPEC_FRAME_FLOWCONTROL_FC_FLAGS_IDX 0
#define ISOTP_SPEC_FRAME_FLOWCONTROL_FC_FLAGS_MASK 0x0F

#define ISOTP_SPEC_FRAME_FLOWCONTROL_BLOCKSIZE_IDX 1
#define ISOTP_SPEC_FRAME_FLOWCONTROL_BLOCKSIZE_MASK 0xFF

#define ISOTP_SPEC_FRAME_FLOWCONTROL_SEPARATION_TIME_IDX 2
#define ISOTP_SPEC_FRAME_FLOWCONTROL_SEPARATION_TIME_MASK 0xFF

#define ISOTP_SPEC_FRAME_FLOWCONTROL_HEADER_END 3

//  Flow control flags
typedef enum {
	ISOTP_SPEC_FC_FLAG_CONTINUE_TO_SEND = 0,
    ISOTP_SPEC_FC_FLAG_WAIT = 1,
    ISOTP_SPEC_FC_FLAG_OVERFLOW_ABORT = 2,
} isotp_flow_control_flags_t;

//  Flow control block size value to ignore FC
#define ISOTP_SPEC_FRAME_FLOWCONTROL_BLOCKSIZE_SEND_WITHOUT_FC 0

//  Flow control requested delay calculations
#define ISOTP_SPEC_FC_SEPERATION_TIME_MS_NONE 0x00
#define ISOTP_SPEC_FC_SEPERATION_TIME_MS_MIN 0x01
#define ISOTP_SPEC_FC_SEPERATION_TIME_MS_MAX 0x7F
#define ISOTP_SPEC_FC_SEPERATION_TIME_MS_SCALAR 1000

#define ISOTP_SPEC_FC_SEPERATION_TIME_uS_MIN 0xF1
#define ISOTP_SPEC_FC_SEPERATION_TIME_uS_MAX 0xF9
#define ISOTP_SPEC_FC_SEPERATION_TIME_uS_SCALAR 100

#ifdef __cplusplus
}
#endif