#ifndef ERRNO_H
#define ERRNO_H

typedef enum {
    SR_OK = 0,
    // flash errors
    SR_FLASH_UNLOCK_ERR,
    SR_FLASH_LOCK_ERR,
    SR_FLASH_WRITE_ERR,
    SR_FLASH_READBACK_ERR,
    SR_FLASH_ERASE_ERR,
    SR_FLASH_INVALID_INPUT,

    // fd-can errors
    SR_FDCAN_CFG_GLOBAL_FILTER_ERR,
    SR_FDCAN_CFG_FILTER_ERR,
    SR_FDCAN_OVER_MAX_FILTERS,
    SR_FDCAN_CFG_FIFO_OVERWRITE_ERR,
    SR_FDCAN_ACTIVATE_NOTIF_ERR,
    SR_FDCAN_TX_MSG_TOO_BIG,
    SR_FDCAN_TX_ERR,
    SR_FDCAN_TIMEOUT,

    // isotp errors
    SR_ISOTP_TX_LEN_ERR,
    SR_ISOTP_INVALID_FRAME,
    SR_ISOTP_ABORTED_TRANSFER,
    SR_ISOTP_TRANSMISSION_TOO_LARGE,
    SR_ISOTP_OUT_OF_ORDER,
    SR_ISOTP_UNEXPECTED_FRAME_TYPE,
    SR_ISOTP_RX_BUFF_TOO_SMALL,
    SR_ISOTP_TIMEOUT,
    SR_ISOTP_TX_INTERRUPTED_BY_RX

} sr_errno_t;

#endif