#ifndef UDS_CONFIG_H
#define UDS_CONFIG_H

#define SID_SESS_CTRL_RQ 0x10
#define SID_SESS_CTRL_RES 0x50

#define SID_ECU_RST_RQ 0x11
#define SID_ECU_RST_RES 0x51

// #define SID_SEC_ACCESS_RQ 0x27
// #define SID_SEC_ACCESS_RES 0x67

#define SID_TESTER_HBT_RQ 0x3E
#define SID_TESTER_HBT_RES 0x7E

#define SID_READ_DATA_RQ 0x22
#define SID_READ_DATA_RES 0x62

#define SID_DOWNLOAD_START_RQ 0x34
#define SID_DOWNLOAD_START_RES 0x74

#define SID_TRNSFR_DATA_RQ 0x36
#define SID_TRNSFR_DATA_RES 0x76

#define SID_DOWNLAOD_EXIT_RQ 0x37
#define SID_DOWNLAOD_EXIT_RES 0x77

#endif